### ISSUE TITLE
libssl-1_1.dll not found - Anaconda

### ISSUE THREAD

**Issue by krozzi** [floxay/python-riot-auth#16]
Tried using the [example code](https://github.com/floxay/python-riot-auth/blob/main/examples/example_auth.py), but it just gives me the error listed below. I did some digging and found out I need OpenSSL so I downloaded it and set up the env variables and whatnot, but it still doesn't seem to work. I'm not really that experienced with this kind of stuff so I apologize if I'm missing out on something really obvious here.

Additional information:
- I'm using Python 3.9 inside a virtual anaconda environment

Full error:
```
Traceback (most recent call last):
  File "C:\Users\ddozzi\PyCharmProjects\valtest\tests\test_login.py", line 13, in <module>
    auth = riot_auth.RiotAuth()
  File "C:\Users\ddozzi\AppData\Roaming\Python\Python39\site-packages\riot_auth\auth.py", line 81, in __init__
    self._auth_ssl_ctx = RiotAuth.create_riot_auth_ssl_ctx()
  File "C:\Users\ddozzi\AppData\Roaming\Python\Python39\site-packages\riot_auth\auth.py", line 100, in create_riot_auth_ssl_ctx
    libssl = ctypes.CDLL("libssl-1_1.dll")
  File "C:\ProgramData\Anaconda3\envs\default\lib\ctypes\__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libssl-1_1.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

OpenSSL Ver:

![image](https://github.com/floxay/python-riot-auth/assets/107476445/67c91081-47da-45b2-a1e0-88641ba68dd6)

Code:

```py
import asyncio
import sys

import riot_auth

# region asyncio.run() bug workaround for Windows, remove below 3.8 and above 3.10.6
if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
# endregion

CREDS = "myuser", "mypass"

auth = riot_auth.RiotAuth()
asyncio.run(auth.authorize(*CREDS))

print(f"Access Token Type: {auth.token_type}\n")
print(f"Access Token: {auth.access_token}\n")
print(f"Entitlements Token: {auth.entitlements_token}\n")
print(f"User ID: {auth.user_id}")

# Reauth using cookies. Returns a bool indicating whether the reauth attempt was successful.
asyncio.run(auth.reauthorize())
```

Please let me know if you need any other information.

**Comment by floxay** [comment]
> Python 3.9 inside a virtual anaconda environment
I suspect this is the issue.

You shouldn't need to install OpenSSL, the module tries to use a DLL which is included with a standard Python install.
However I am not sure about anaconda and conda envs. It might be that this DLL is simply not included or has a different filename; `libssl-1_1-x64.dll` perhaps?

**Comment by krozzi** [comment]
Yes! You're correct, it is called `libssl-1_1-x64.dll`! (found in `C:\ProgramData\Anaconda3\envs\default\Library\bin`). 

Tested to make sure it worked using
```py
import ctypes

libssl = ctypes.CDLL("libssl-1_1-x64.dll")
```
and it runs without errors. Unlike when running it without the "-x64".

Would adding a try/except block to [this line](https://github.com/floxay/python-riot-auth/blob/b68326b709c4ab9bef25d55ceb1d36324eb7dbba/riot_auth/auth.py#L100C1-L100C1) sort this out? I'm not sure if that's the best method, but that's all I can think of right now.

**Comment by krozzi** [comment]
Thank you
