### ISSUE TITLE
invalid_session_id

### ISSUE THREAD

**Issue by DestroyerDarkNess** [floxay/python-riot-auth#22]
Hello, good project, I have a small problem, for some reason when I authenticate it returns the Post:

`{"type":"error","error":"invalid_session_id","country":"co"}`

Any idea what field I'm missing from the **body**?

` body = {
                "acr_values": "",
                "claims": "",
                "client_id": "riot-client",
                "code_challenge": "",
                "code_challenge_method": "",
                "nonce": token_urlsafe(16),
                "redirect_uri": "http://localhost/redirect",
                "response_type": "token id_token",
                "scope": "openid link ban lol_region account",
            }`

**Comment by floxay** [comment]
I don't understand why you would ask this, do you have an minimal reproducible example?

**Comment by DestroyerDarkNess** [comment]
I mean that I downloaded your project, but for some reason the post returns an error. at [HERE](https://github.com/floxay/python-riot-auth/blob/6c4cafcfcdc55ba6421cb88fb3d3010c6e19e9ba/riot_auth/auth.py#L269C19-L269C19)  .

Are there any fields missing from the submitted data? That's what I was wondering.
