### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by chickendie** [floxay/python-riot-auth#27]
I used it the first time, and when I used it the second time I still got this error. How to fix this error? Thank you

**Comment by chickendie** [comment]
And when the request is made about 8 times, you will receive a notification from the server "Computers Say No". It takes 15 - 30 minutes before it can be used again

**Comment by kevinyasuo** [comment]
I have this problem too
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://auth.riotgames.com/api/v1/authorization')

**Comment by chickendie** [comment]
> I have this problem too aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://auth.riotgames.com/api/v1/authorization')

I found the error of this problem was due to token_urlsafe , which generated an invalid string. The valid character strings I collected are strings like this xxxxxxxx-xxxxxxxxxxx..........


As for error 498, I still haven't found a solution other than waiting 15 - 30 minutes to use it again.

**Comment by floxay** [comment]
> I found the error of this problem was due to token_urlsafe , which generated an invalid string. The valid character strings I collected are strings like this xxxxxxxx-xxxxxxxxxxx..........

For the user agent or the nonce?

**Comment by chickendie** [comment]
> > I found the error of this problem was due to token_urlsafe , which generated an invalid string. The valid character strings I collected are strings like this xxxxxxxx-xxxxxxxxxxx..........
> 
> For the user agent or the nonce?

For user-agent , Here are a few valid agents I gathered : 
- LnS01XKqrWgZ6iGlldreHJrd7wx3-Ycuqn2cxFlPfQvwzWosh4SaFF3KGVcjqGPw79N-hGAjmKwIiCX4VyhCjcwe-jmgz63ijC9OA8APTqAlIk2
- VXpTemApJMMK-VyUNRGEfYKLC6eSA6YxzRtRDQSQCO2D6pDgiswGuHHaeAHQG-5jJphsqDhXAVdIx6Yee5-XOlNFhrf6HZ6mfLDllCyAkWWdaOTNnJMbqPyDlt1XjaFN2Tb6ftu-bPKEaswqCN7r

**Comment by floxay** [comment]
I doubt this means anything.

If you are trying to auth with multiple accounts over a short period of time using the same IP errors are expected.

**Comment by chickendie** [comment]
I use a proxifier so that 1 account has a different ip

**Comment by chickendie** [comment]
![image](https://github.com/user-attachments/assets/03de51b4-4429-4ab1-801e-919179add35b)
Here's what it looks like if I use the valid strings I collected

![image](https://github.com/user-attachments/assets/3d7db20e-ffb2-49d2-a74b-ef5ec6541c5a)
And here is an image of me using token_urlsafe to generate random strings (if it is invalid, the situation will appear as shown).

**Comment by kevinyasuo** [comment]
> > > I found the error of this problem was due to token_urlsafe , which generated an invalid string. The valid character strings I collected are strings like this xxxxxxxx-xxxxxxxxxxx..........
> > 
> > 
> > For the user agent or the nonce?
> 
> For user-agent , Here are a few valid agents I gathered :
> 
> * LnS01XKqrWgZ6iGlldreHJrd7wx3-Ycuqn2cxFlPfQvwzWosh4SaFF3KGVcjqGPw79N-hGAjmKwIiCX4VyhCjcwe-jmgz63ijC9OA8APTqAlIk2
> * VXpTemApJMMK-VyUNRGEfYKLC6eSA6YxzRtRDQSQCO2D6pDgiswGuHHaeAHQG-5jJphsqDhXAVdIx6Yee5-XOlNFhrf6HZ6mfLDllCyAkWWdaOTNnJMbqPyDlt1XjaFN2Tb6ftu-bPKEaswqCN7r
> * NQ9BKt-sqYdaxHHexhgSCENruCr8HDxRGZqj6jHPYh8CoQ-gspWVejGIEylyFbGTt0f8UGagooQKa9FIqUJitKi41ppsL9gvpcXlrBDb5-JViUSFbc27KwKPBHmzzMFJ12eMybfuvgFM4wiIt9UP

Hi how do you gather the User-agent?

**Comment by chickendie** [comment]
> > > > I found the error of this problem was due to token_urlsafe , which generated an invalid string. The valid character strings I collected are strings like this xxxxxxxx-xxxxxxxxxxx..........
> > > 
> > > 
> > > For the user agent or the nonce?
> > 
> > 
> > For user-agent , Here are a few valid agents I gathered :
> > 
> > * LnS01XKqrWgZ6iGlldreHJrd7wx3-Ycuqn2cxFlPfQvwzWosh4SaFF3KGVcjqGPw79N-hGAjmKwIiCX4VyhCjcwe-jmgz63ijC9OA8APTqAlIk2
> > * VXpTemApJMMK-VyUNRGEfYKLC6eSA6YxzRtRDQSQCO2D6pDgiswGuHHaeAHQG-5jJphsqDhXAVdIx6Yee5-XOlNFhrf6HZ6mfLDllCyAkWWdaOTNnJMbqPyDlt1XjaFN2Tb6ftu-bPKEaswqCN7r
> > * NQ9BKt-sqYdaxHHexhgSCENruCr8HDxRGZqj6jHPYh8CoQ-gspWVejGIEylyFbGTt0f8UGagooQKa9FIqUJitKi41ppsL9gvpcXlrBDb5-JViUSFbc27KwKPBHmzzMFJ12eMybfuvgFM4wiIt9UP
> 
> Hi how do you gather the User-agent?

I let them run and print out user-agent with valid requests

**Comment by floxay** [comment]
Marking this as "invalid" since the old auth flow this package uses is no longer functional.

**Comment by floxay** [comment]
This should be resolved with v1.0.7.
