### ISSUE TITLE
Support for 2-fa

### ISSUE THREAD

**Issue by typhonshambo** [floxay/python-riot-auth#4]
The auth gives error when the account have 2fa enabled!

**Comment by Aewait** [comment]
I modify code from [Prodzify/Riot-auth](https://github.com/Prodzify/Riot-auth), transfering request cookie to aiohttp cookie_jar, now 2fa is supported login and cookie reauth with [python-riot-auth](https://github.com/floxay/python-riot-auth)

https://github.com/Aewait/Kook-Valorant-Bot/blob/main/code/endpoints/EzAuth.py

you can see example at https://github.com/Aewait/Kook-Valorant-Bot/blob/937206e3f3849bae06d1636815aade2421a0e1b3/code/endpoints/ApiHandler.py#L68-L82

when EzAuth object get token successful, you could get RiotAuth object by using EzAuth.get_RiotAuth

https://github.com/Aewait/Kook-Valorant-Bot/blob/937206e3f3849bae06d1636815aade2421a0e1b3/code/endpoints/EzAuth.py#L219-L235
